package:
  name: perl-chandra-time
  version: !!str 0.9.2

source:
  url: file:///proj/sot/ska/pkgs/Chandra-Time-0.9.2.tar.gz
  patches:
  # the env_gxx.patch sets the CC and LD to be the ENV{CXX) instead of 'g++'
  # in the Makefile.PL
    - env_gxx.patch


requirements:
  host:
    - gcc_linux-64
    - gxx_linux-64
    - perl
    - perl-core-deps
    - xtime
  run:
    - gcc_linux-64
    - gxx_linux-64
    - perl
    - perl-core-deps
    - xtime

test:
  # Perl 'use' tests
  imports:
    - Chandra::Time

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

