package:
  name: pgplot
  version: 5.2.2

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
  url: file:///proj/sot/ska/pkgs/pgplot-5.2.2-3_05.tar.gz

build:
  number: 1

requirements:
  build:
    - pkg-config
    - libpng
  run:
    - libpng
