package:
  name: perl-ska-classic
  version: 0.6

source:
  url: https://cxc.harvard.edu/mta/ASPECT/skare3-static-pkgs/skaclassic-0.6.tar.gz

requirements:
  build:
    - perl
  run:
    - perl
    - perl-core-deps
    - chandra.time
