package:
  name: perl-core-deps
  version: 0.2

source:
  url:  file:///proj/sot/ska/pkgs/cpan-core-0.2.tar.gz

requirements:
  build:
   - perl
   - perl-extutils-f77
   - perl-app-cpanminus
   - pkg-config
   - libpng
   - cfitsio
   - pgplot [linux]
   - xtime
   - gsl
   - openssl
   - openblas
   - gcc ==4.8.5 [linux]
   - libgcc ==4.8.5 [linux]
   - libgfortran [linux]
   - python
run:
   - perl
   - perl-app-cpanminus
   - pkg-config
   - libpng
   - cfitsio
   - pgplot [linux]
   - xtime
   - gsl
   - openssl
   - openblas
   - libgcc ==4.8.5 [linux]
   - libgfortran [linux]
   - python

build:
   number: 0







