package:
  name: perl
  version: 5.18.2


source:
  url: http://www.cpan.org/src/5.0/perl-5.18.2.tar.gz
  md5: 373f57ccc441dbc1812435f45ad20660

requirements:
  build:
    - pkg-config
    - gcc ==4.8.5 [linux]
    - libgcc ==4.8.5 [linux]
  run:
    - pkg-config
    - libgcc ==4.8.5 [linux]


test:
  commands:
     - perl -V

build:
   number: 0