package:
  name: perl-cxc-sysarch
  version: !!str 1.00

source:
  url: https://cxc.harvard.edu/mta/ASPECT/skare3-static-pkgs/CXC-SysArch-1.00.tar.gz
#  patches:
   # List any patch files here
   # - fix.patch


requirements:
  build:
    - perl
    - perl-core-deps

  run:
    - perl
    - perl-core-deps


test:
  # Perl 'use' tests
  imports:
    - CXC::SysArch
 

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

